### ISSUE TITLE
DOCS enhacement

### ISSUE THREAD

**Issue by EgorBron** [TheStngularity/JSAndCSSPack#6]
An idea for docs: add image examples for each thing in pack. Example:
```md
# title elem
`example code`
![example view]()
Doc-table
```

**Comment by EgorBron** [comment]
sry, I can't edit labels for this(

**Comment by EgorBron** [comment]
@TheStngularity suka tvoy mat', не игнорь

**Comment by stngularity** [comment]
Как бы тебе сказать, мне лень

**Comment by EgorBron** [comment]
> Как бы тебе сказать, мне лень

Тогда вылей коммиты, ты же уже много чего сделал

**Comment by EgorBron** [comment]
git add . && git commit -m "push all" && git push origin master
